### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ptichalouf** [eXqusic/AnimationsBeFastPlus#11]
**Describe the bug**
Jailbreak detection bypass didn’t work with a-bypass. If I have animationbefastplus activated. I can’t launch my bank app or call of duty mobile

**To Reproduce**
Install a-bypass launch any app with jailbreak detection. Call of duty is free and work great in that exemple. Activate your tweak call of won’t work. Desactivate the tweak, the jailbreak detection bypass work great. 

**Expected behavior**
Correct this conflict like that I can use animationbefastplus on my device. It’s always disable for now. 

**iDevice Information (Must include information below!):
 - Device: iPhone X , iPhone 11 Pro Max. iPad Pro 13 2018
 - iOS Version: 13.5
 - Tweak Version: Latest

**Comment by eXqusic** [comment]
Have you tried disabling animationsbefastplus in those apps?

**Comment by ptichalouf** [comment]
How can I be so stupid. Could you forget this bug and me forever. Sorry for wasting your time dude lol 

Envoyé de mon iPhone
