### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by sharp7x** [eXqusic/AnimationsBeFastPlus#15]
i cant link animplus on cydia or my account even I paid it pls help

**Comment by sharp7x** [comment]
![Uploading 990BE4A2-400E-43E5-A531-62800C1E1632.jpeg…]()

**Comment by sharp7x** [comment]
![D68D3BFC-F377-4DB0-B791-9EF52D05D069](https://user-images.githubusercontent.com/61109432/111113468-cd425180-859c-11eb-86d4-0c732a7a4006.jpeg)

**Comment by sharp7x** [comment]
![Uploading 47DB117B-EA44-41B8-B67E-C9C1F6C6F2AE.jpeg…]()

**Comment by sharp7x** [comment]
![Uploading 0A6FC2F7-5898-4ABA-9AF9-F6B440897595.jpeg…]()

**Comment by eXqusic** [comment]
You will need to contact Packix repo for help with that as I only use their site to host it.
Id suggest using Zebra for a package manager.
