### ISSUE TITLE
[Bug]APP crash randomly when opening

### ISSUE THREAD

**Issue by unrealwzg** [eXqusic/AnimationsBeFastPlus#4]
**Describe the bug**
some APP will crash randomly when opening it at the first time, no matter what the app is. when trying to open it again, the app will open normally.
edit:seems the native app will not crash only app installed from appstore will.

**Crash log**
https://pastebin.com/MkX0CnnY

**iDevice Information (Must include information below!):
 - Device: Iphone x
 - iOS Version: 13.3.1
 - Tweak Version:latest
 - Tweak List: https://pastebin.com/nJBVfM8b

**Comment by eXqusic** [comment]
Can you please provide the crash report from Settings > Privacy > Analytics

**Comment by joshHuang02** [comment]
I have the same problem but only with cod (call of duty mobile), I can provide analytics report and all the other info if you want

**Comment by bazz318** [comment]
Have the same problem,one of my app still crashing. Only works wiem tweak deleted :(

iPhone X
iOS 13.3
tweak version: latest

**Comment by eXqusic** [comment]
This issue is now resolved in the latest version.
