### ISSUE TITLE
[Bug] PreferenceLoader - Unrecognized version

### ISSUE THREAD

**Issue by Chibibowa** [eXqusic/AnimationsBeFastPlus#6]
**Describe the bug**
When I try to install AnimationsBeFastPlus (FacebookDarkMode faces this problem too btw), the package depends on preference loader, despite having it installed. And yes, I have added the rpetri.ch repo (but the preference loader is marked as beta and not what you ask as a dependency. Check screenshot below).

PS: Yes, I purchased the tweak, see screenshot as proof.

PS2: I had to reinstall the original preference loader I had saved to get it to work. However, it is possible to install animationsbefastplus deb by using filza AFTER installing the preference loader found in Sileo (see image for exact version), (installing AnimationsBeFastPlus via Sileo will give you a dependency error, despite having the tweak manually installed beforehand, unless I manually reinstall the deb version I had saved).

**To Reproduce**
Nothing spectacular. See screenshot below (I have manually fixed the problem by saving the deb before restoring, because I knew this would happen).

**Screenshots/Video**
Here: https://mega.nz/folder/zgc3nYoa#ErNfk7Zqi3GzgrCCKiAfMg

**Crash log**
None.

**iDevice Information (Must include information below!):
 - Device: iPhone 8 Plus
 - iOS Version: 13.4.1
 - Tweak Version: Latest (as of 21 April 2020)
 - Tweak List: Not really required, but since you ask for it, here you go; The problem is clearly described in the picture available on my mega cloud.

Pastebin link: https://pastebin.com/KZYRszhV
Sources list: https://pastebin.com/s08gmZ62 (default repos not included)

**Comment by eXqusic** [comment]
This will be fixed in the next version I release.

**Comment by Chibibowa** [comment]
Thanks. Keep up the good work ! It’s a must-have tweak ! :-)

**Comment by eXqusic** [comment]
This issue is now resolved in v4.8
