### ISSUE TITLE
Messages Blank Screen

### ISSUE THREAD

**Issue by diddlywoo** [eXqusic/AnimationsBeFastPlus#9]
When using this with the stock messages app, about 40% of the time when tapping on a convo it just shows a blank screen. Must back out and reopen. Happens often. 11 Pro on 13.5

**Comment by eXqusic** [comment]
Can you provide a list of tweaks?
Im unable to reproduce this issue as I have the same setup and use messages a lot..

**Comment by eXqusic** [comment]
Closed due to no response.

**Comment by diddlywoo** [comment]
AppList (applist) v1.5.16 by Ryan Petrich  via BigBoss
APT (apt) v1.8.2-3 by Unknown via Bingner/Elucubratus
APT (apt-key) (apt-key) v1.8.2-1 by Unknown via Bingner/Elucubratus
APT 1.4 Transitional (apt1.4) v1:0 by Unknown via Bingner/Elucubratus
Base Structure (base) v1-5 by Unknown via Bingner/Elucubratus
Bourne-Again SHell (bash) v5.0.3-2 by Unknown via Bingner/Elucubratus
PhaseMoon13 (be.submanifold.phasemoon13) v0.0.1-73+debug by rainwolf  via
none
WeatherLock13 (be.submanifold.weatherlock13) v0.0.1-51+debug by rainwolf
 via none
Berkeley DB (berkeleydb) v6.2.32-1 by Unknown via Bingner/Elucubratus
bzip2 (bzip2) v1.0.6-1 by Unknown via Bingner/Elucubratus
CA Certs (ca-certificates) v0.0.2 by Unknown via Bingner/Elucubratus
CoolFolder (com.4nni3.coolfolder) v2.7-2 by 4nni3  via Packix
AnimationsBeFastPlus (com.adamseiter.animationsbefastplus) v4.8 by eXqusic
via Packix
BetterCCXI (com.atwiiks.betterccxi) v1.6.0 by ATWiiks via Packix
Cydia Repo Icon (com.ceadd.icon) v2.3 by ceadd via Ceadd's Repo
AppStore++ (com.cokepokes.appstoreplusplus) v0.9.11 by CokePokes via
Phantom Apps LLC
libCSPreferences (com.creaturecoding.libcspreferences) v1.4.7 by
CreatureSurvive  via CreatureCoding Repo
shuffle (com.creaturecoding.shuffle) v1.2.9 by CreatureSurvive  via
CreatureCoding Repo
libCSColorPicker (com.creaturesurvive.libcscolorpicker) v1.0.3 by
CreatureSurvive  via CreatureCoding Repo
BarinProgress (com.cydiageek.barinprogress) v1.0.1 by CydiaGeek  via BigBoss
Social Downloader (com.elias.socialdownloader) v1.2-1 by elias via Packix
Substitute (com.ex.substitute) v0.1.13 by comex  via Bingner/Elucubratus
iCleaner Pro (com.exile90.icleanerpro) v7.8.3 by Ivano Bilenchi  via Ivano
Bilenchi's Beta Repo
AmazoNite (com.foxfort.amazonite) v2.0.0 by FoxfortMobile via Packix
Deluminator (com.foxfort.deluminator) v3.0.7 by FoxfortMobile via Packix
FacebookDarkMode (com.foxfort.facebookdarkmode) v2.6.4 by FoxfortMobile via
Packix
FoxFort Tools (com.foxfort.foxforttools) v1.1.2 by FoxfortMobile via Packix
libfoxfortsplash (com.foxfort.libfoxfortsplash) v1.1.3 by FoxfortMobile via
Packix
libfoxfortutils (com.foxfort.libfoxfortutils) v1.0.20 by FoxfortMobile via
Packix
VolumePercent (com.gilshahar7.volumepercent) v1.0 by gilshahar7 via Packix
TransparentDock13 (com.ichitaso.transparentdock13) v0.0.2 by ichitaso via
ichitaso
CallBlocker (com.imkpatil.callblocker) v2.0.3 by P2KDev  via Packix
FBSpNOsor (com.jacobcxdev.fbspnosor) v1.2.8 by JacobCXDev  via Packix
libJCX (com.jacobcxdev.libjcx) v1.1.0 by JacobCXDev  via Chariz
CCModules (com.jailbreak365.safeccmodules) v1.5-1 by jailbreak365  via
jailbreak365's Repo
RealCC (com.jakeashacks.realcc) v1.0.2 by Jake James  via BigBoss
GoodWiFi (com.julioverne.goodwifi) v0.0~beta5a by julioverne via julioverne
NtSpeed (com.julioverne.ntspeed) v0.2~beta7 by julioverne via julioverne
Spotilife (com.julioverne.spotilife) v1.1a by julioverne via julioverne
Locale Profiles in UTF-8 (com.linusyang.localeutf8) v1.0-1 by Linus Yang
 via BigBoss
ReProvision (com.matchstic.reprovision) v0.5.2~EOL by Matt Clarke  via
Matchstic
NeoFetch-iOS (com.matdev.neofetch-ios) v1.0.0 by MatDev via Packix
Glasklart (com.modmyi.glasklart2) v5.52 by Max Rudberg  via ModMyi
ColorMeNotifs (com.mrgcgamer.colormenotifs) v1.4.2 by MrGcGamer via Packix
CCSupport (com.opa334.ccsupport) v1.2.2 by opa334 via opa334's Repo
Choicy (com.opa334.choicy) v1.2.2 by opa334  via opa334's Repo
Safari Plus (com.opa334.safariplus) v1.7.12 by opa334  via opa334's Repo
NudeKeys (iOS 12) (com.orangebananaspy.nudekeysios12) v1.0.0~b8 by
Orangebananaspy  via Orangebananaspy
TweakReviewsDB (com.pixelomer.tweakreviews-db) v0.6 by PixelOmer via
PixelOmer's Repo
LetMeBlock (com.ps.letmeblock) v0.0.7.1 by PoomSmart via PoomSmart's Repo
Cylinder (com.r333d.cylinder) v1.1 by Reed Weichler  via BigBoss
GrooveTube (com.revulate.groovetube) v1.0 by Revulate via Dynastic Repo
Harmony (com.revulate.harmony) v2.0.1 by Revulate via Dynastic Repo
Delta (com.rileytestut.delta) v1.1.1 by Rileytestut via Delta Repo
RocketBootstrap (com.rpetrich.rocketbootstrap) v1.0.9 by Ryan Petrich  via
BigBoss
Substrate Safe Mode (com.saurik.substrate.safemode) v0.9.6003 by Jay
Freeman (saurik)  via Bingner/Elucubratus
Togglow (com.smokin1337.togglow) v1.0.8 by smokin1337  via iDeviceHacked
[lovely day to be jailbroken]
CrashReporter (SparkDev) (com.spark.crash-reporter) v1.17.2 by Revulate
 via Revulate's Repo
libcrashreport (SparkDev) (com.spark.libcrashreport) v1.1.2 by Revulate
 via Revulate's Repo
libpackageinfo (SparkDev) (com.spark.libpackageinfo) v1.1.4 by Revulate
 via Revulate's Repo
libsparkcolourpicker (com.spark.libsparkcolourpicker) v1.0.0 by Spark via
SparkDev
libsymbolicate (SparkDev) (com.spark.libsymbolicate) v1.9.2 by Revulate
 via Revulate's Repo
SnowBoard (com.spark.snowboard) v1.3.3~Beta3 by Spark via SparkDev
TechSupport Framework (SparkDev) (com.spark.techsupport) v1.5.2 by Revulate
 via Revulate's Repo
UHB - iOS 9/10/11/12 (Untrusted Hosts Blocker)
(com.thireus.untrustedhostsblocker9) v1.7.1 by Thireus  via Thireus Repo
Mega UHB IPv4+6 - iOS 9/10/11/12 - MUHB IPv4+6 (Mega Untrusted Hosts
Blocker IPv4 and IPv6) (com.thireus.untrustedhostsblockermega) v2.1.1 by
Thireus  via Thireus Repo
Filza File Manager (com.tigisoftware.filza) v3.7.5-9 by TIGI Software  via
BigBoss
YouTube Tools (com.yourepo.jpet26.youtubetools1) v4.0 by Justin Petkovic
 via jpet26 Source - YouRepo
MessageColors (com.yourepo.restiveconch.messagecolors) v1.5 by RestiveConch
 via RestiveConch - YouRepo
Core Utilities (coreutils) v8.31-1 by Unknown via Bingner/Elucubratus
Core Utilities (/bin) (coreutils-bin) v8.31-1 by Unknown via
Bingner/Elucubratus
Cydia Installer (cydia) v1.1.34 by Jay Freeman (saurik)  via
Bingner/Elucubratus
Cydia Translations (cydia-lproj) v1.1.32~b1 by Jay Freeman (saurik)  via
Bingner/Elucubratus
Darwin Tools (darwintools) v1.1-1 by Unknown via Bingner/Elucubratus
Debian Utilities (debianutils) v4.8.6-1 by Unknown via Bingner/Elucubratus
Diff Utilities (diffutils) v3.6-1 by Unknown via Bingner/Elucubratus
diskdev-cmds (diskdev-cmds) v593.221.1-1 by Unknown via Bingner/Elucubratus
Debian Packager (dpkg) v1.19.7-1 by Unknown via Bingner/Elucubratus
Essential (essential) v0-2 by Unknown via Bingner/Elucubratus
file (file) v5.35-2 by Unknown via Bingner/Elucubratus
Find Utilities (findutils) v4.6.0-2 by Unknown via Bingner/Elucubratus
iPhone Firmware (/sbin) (firmware-sbin) v0-1 by Unknown via
Bingner/Elucubratus
Gawk (gawk) v4.2.1-1 by Unknown via Bingner/Elucubratus
GNU Cryptography (gcrypt) v1.8.3-1 by Unknown via Bingner/Elucubratus
gettext (gettext) v0.19.8-1 by Unknown via Bingner/Elucubratus
GnuPG (gnupg) v2.2.11-2 by Unknown via Bingner/Elucubratus
GnuTLS (gnutls) v3.5.19-1 by Unknown via Bingner/Elucubratus
grep (grep) v3.1-1 by Unknown via Bingner/Elucubratus
gzip (gzip) v1.9-1 by Unknown via Bingner/Elucubratus
Kalm (hi.my.name.is.ubik.kalm) v1.4.3 by ubik  via Chariz
Launch Daemon Controller (launchctl) v23-1 by Unknown via
Bingner/Elucubratus
Link Identity Editor (ldid) v2:2.1.2+g5420cb5-1 by Jay Freeman (saurik)
 via Bingner/Elucubratus
APT Strict (lib) (libapt) v1.8.2-1 by Unknown via Bingner/Elucubratus
APT (libapt-pkg) (libapt-pkg5.0) v1.8.2-1 by Unknown via Bingner/Elucubratus
Assuan (libassuan) v2.5.1-1 by Unknown via Bingner/Elucubratus
GNU Multiple Precision Arithmetic Library (libgmp10) v6.1.2-1 by Unknown
via Bingner/Elucubratus
GnuPG Errors (libgpg-error) v1.32-1 by Unknown via Bingner/Elucubratus
libidn2 (libidn2) v6.1.2-1 by Unknown via Bingner/Elucubratus
KSBA (libksba) v1.3.5-1 by Unknown via Bingner/Elucubratus
libplist (libplist) v2.0.0-2 by Unknown via Bingner/Elucubratus
libskittycolor (libskittycolor) v1.0 by Skitty via Skitty's Repo
OpenSSL 1.0 Libraries (libssl1.0) v1.0.2s-1 by Unknown via
Bingner/Elucubratus
OpenSSL 1.1.1 Libraries (libssl1.1.1) v1.1.1c-1 by Unknown via
Bingner/Elucubratus
libtasn1 (libtasn1) v4.13-1 by Unknown via Bingner/Elucubratus
libunistring (libunistring) v0.9.10-1 by Unknown via Bingner/Elucubratus
LZ4 (lz4) v1.7.5-1 by Unknown via Bingner/Elucubratus
LZMA Utils (lzma) v2:4.32.7-2 by Unknown via Bingner/Elucubratus
Eclipse for iOS 13 (me.gmoran.eclipse13) v7.0.2 by Guillermo Morán (fr0st)
via Packix
ClearWidgets (me.lightmann.clearwidgets) v1.0.1.1 by Lightmann  via BigBoss
TransparentNotif (me.lightmann.transparentnotif) v1.0.6.3-1 by Lightmann
 via BigBoss
New Curses (ncurses) v6.1+20181013-1 by Unknown via Bingner/Elucubratus
New Curses (ncurses5-libs) v5.9-1 by Unknown via Bingner/Elucubratus
AppSync Unified (net.angelxwind.appsyncunified) v76.0 by Linus Yang,
Karen/あけみ  via Karen/あけみ's Repo
Nettle (nettle) v3.4.1-1 by Unknown via Bingner/Elucubratus
New GNU Portable Threads (npth) v1.6-1 by Unknown via Bingner/Elucubratus
BigBoss Icon Set (org.thebigboss.repo.icons) v1.0 by Unknown via
Bingner/Elucubratus
p11-kit (p11-kit) v0.23.12-1 by Unknown via Bingner/Elucubratus
7-zip (POSIX) (p7zip) v16.02-1 by Unknown via Bingner/Elucubratus
PreferenceLoader (preferenceloader) v2.2.4 by Sam Bingner  via BigBoss
Profile Directory (profile.d) v0-1 by Unknown via Bingner/Elucubratus
readline (readline) v8.0-1 by Unknown via Bingner/Elucubratus
CocoaTop (ru.domo.cocoatop64) v2.0.2-1+debug by Domo via NotMyTweaks Repo
Unc0ver Policy Softener (science.xnu.substituted) v1.0.0 by pwn20wnd  via
Local Repository
sed (sed) v4.5-1 by Unknown via Bingner/Elucubratus
shell-cmds (shell-cmds) v118-8 by Unknown via Bingner/Elucubratus
system-cmds (system-cmds) v790.30.1-2 by Unknown via Bingner/Elucubratus
Tape Archive (tar) v1.30-2 by Unknown via Bingner/Elucubratus
HideDots (tk.1di4r.hidedots11) v1.5 by 1di4r  via BigBoss
UIKit Tools (uikittools) v1.1.17-1 by Unknown via Bingner/Elucubratus
unrar (unrar) v5.6.4-1 by Unknown via Bingner/Elucubratus
unzip (unzip) v6.0+deb9u1-1 by Unknown via Bingner/Elucubratus
Alderis Color Picker (ws.hbang.alderis) v1.0.1 by HASHBANG Productions  via
Chariz
Cephei Tweak Support (ws.hbang.common) v1.15.1 by HASHBANG Productions  via
Chariz
NewTerm (iOS 10 – 13) (ws.hbang.newterm2) v2.4 by HASHBANG Productions  via
Chariz
Spectrum (xyz.skitty.spectrum) v1.0.1-1 by Skitty & EvenDev via Skitty's
Repo
Zebra (xyz.willy.zebra) v1.1.10 by Wilson Styres  via Zebra
System Info (xyz.xninja.systeminfo) v2.7.2-1 by ARX8x via ARX8x
XZ Utils (xz) v5.2.4-4 by Unknown via Bingner/Elucubratus
zip (zip) v2.32-1 by Unknown via Bingner/Elucubratus


Very sorry for being late!
